In [5]:
import numpy as np
import pandas as pd

In [6]:
from IPython.display import Markdown
Markdown("# Creating a Data frame" )

# Creating a Data frame

In [14]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [16]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
columns =["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
from IPython.display import Markdown
Markdown("# Selections and Indexing of columns" )

# Selections and Indexing of columns

In [19]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [21]:
df["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [22]:
df[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [23]:
from IPython.display import Markdown
Markdown("# Creating new column" )

# Creating new column

In [24]:
df2["Desiginations"]=["Doctor","engineering","doctor","enginering"]

In [25]:
df2

    Name  Age      City  Salary Desiginations
0   John   28  New York   65000        Doctor
1   Anna   34     Paris   70000   engineering
2  Peter   29    Berlin   62000        doctor
3  Linda   42    London   85000    enginering

In [26]:
from IPython.display import Markdown
Markdown("# Remove a column ")

# Remove a column

In [31]:
df2.drop('Desiginations',axis=1,inplace=True)

In [32]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
df2.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [34]:
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [35]:
from IPython.display import Markdown
Markdown("# Selecting a Raw")

# Selecting a Raw

In [46]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [48]:
df2.loc[0:1]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [42]:
from IPython.display import Markdown
Markdown("# Selecting subsets of Raws and Columns" )

# Selecting subsets of Raws and Columns

In [44]:
df2.loc[2:3,["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [45]:
from IPython.display import Markdown
Markdown("# Conditional Selections " )

# Conditional Selections

In [49]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [50]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [52]:
df2[(df2["Age"]>30) & (df2["City"]=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

In [53]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [55]:
df2[(df2["Salary"]<70000)&(df2["Age"]<40)]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [56]:
df2[~(df2["Age"]>30)]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000