In [2]:
import numpy as np
import pandas as pd

In [3]:
import pandas as pd

data = {
    "Name": ["Aman", "Ravi", "Neha", "Priya", "Aman", "Karan"],
    "Age": [20, 21, 19, 22, 20, 23],
    "Marks": [85, 60, 92, 45, 85, 72],
    "City": ["Jaipur", "Delhi", "Jaipur", "Mumbai", "Jaipur", "Delhi"],
    "Department": ["CSE", "IT", "CSE", "IT", "CSE", "AI"]
}

df = pd.DataFrame(data)

In [4]:
df

    Name  Age  Marks    City Department
0   Aman   20     85  Jaipur        CSE
1   Ravi   21     60   Delhi         IT
2   Neha   19     92  Jaipur        CSE
3  Priya   22     45  Mumbai         IT
4   Aman   20     85  Jaipur        CSE
5  Karan   23     72   Delhi         AI

In [6]:
df[["Name","Marks"]]

    Name  Marks
0   Aman     85
1   Ravi     60
2   Neha     92
3  Priya     45
4   Aman     85
5  Karan     72

In [12]:
df.iloc[0:3]

   Name  Age  Marks    City Department
0  Aman   20     85  Jaipur        CSE
1  Ravi   21     60   Delhi         IT
2  Neha   19     92  Jaipur        CSE

In [13]:
df.loc[2]

Name            Neha
Age               19
Marks             92
City          Jaipur
Department       CSE
Name: 2, dtype: object

In [14]:
df.loc[df["Marks"]>80,"Name"]

0    Aman
2    Neha
4    Aman
Name: Name, dtype: str

In [18]:
df.loc[df["Age"]>=20,"Name"]

0     Aman
1     Ravi
3    Priya
4     Aman
5    Karan
Name: Name, dtype: str

In [16]:
df[df["City"]=="Jaipur"]

   Name  Age  Marks    City Department
0  Aman   20     85  Jaipur        CSE
2  Neha   19     92  Jaipur        CSE
4  Aman   20     85  Jaipur        CSE

In [19]:
df[(df["Marks"]>60) & (df["Age"]>20)]

    Name  Age  Marks   City Department
5  Karan   23     72  Delhi         AI

In [20]:
df[(df["City"]=="Jaipur") | (df["City"]=="Delhi")]

    Name  Age  Marks    City Department
0   Aman   20     85  Jaipur        CSE
1   Ravi   21     60   Delhi         IT
2   Neha   19     92  Jaipur        CSE
4   Aman   20     85  Jaipur        CSE
5  Karan   23     72   Delhi         AI

In [21]:
df[(df["Marks"]>45) & (df["Marks"]<85)]

    Name  Age  Marks   City Department
1   Ravi   21     60  Delhi         IT
5  Karan   23     72  Delhi         AI

In [22]:
df

    Name  Age  Marks    City Department
0   Aman   20     85  Jaipur        CSE
1   Ravi   21     60   Delhi         IT
2   Neha   19     92  Jaipur        CSE
3  Priya   22     45  Mumbai         IT
4   Aman   20     85  Jaipur        CSE
5  Karan   23     72   Delhi         AI

In [23]:
df[(df["Department"]=="CSE") & (df["Marks"]>80)]

   Name  Age  Marks    City Department
0  Aman   20     85  Jaipur        CSE
2  Neha   19     92  Jaipur        CSE
4  Aman   20     85  Jaipur        CSE

In [34]:
def Garde(x):
    if x>80:
        return "A"
    else:
        return "B"

In [35]:
df["Grade"]=df["Marks"].apply(Garde)

In [36]:
df

    Name  Age  Marks    City Department Grade
0   Aman   20     85  Jaipur        CSE     A
1   Ravi   21     60   Delhi         IT     B
2   Neha   19     92  Jaipur        CSE     A
3  Priya   22     45  Mumbai         IT     B
4   Aman   20     85  Jaipur        CSE     A
5  Karan   23     72   Delhi         AI     B

In [37]:
df["grade"]=df["Marks"].apply(lambda x:"A" if x>=80 else "B")

In [38]:
df

    Name  Age  Marks    City Department Grade grade
0   Aman   20     85  Jaipur        CSE     A     A
1   Ravi   21     60   Delhi         IT     B     B
2   Neha   19     92  Jaipur        CSE     A     A
3  Priya   22     45  Mumbai         IT     B     B
4   Aman   20     85  Jaipur        CSE     A     A
5  Karan   23     72   Delhi         AI     B     B

In [39]:
df["Marks"].apply(lambda x:x+5)

0    90
1    65
2    97
3    50
4    90
5    77
Name: Marks, dtype: int64

In [42]:
df.drop('Age',axis=1)

    Name  Marks    City Department Grade grade
0   Aman     85  Jaipur        CSE     A     A
1   Ravi     60   Delhi         IT     B     B
2   Neha     92  Jaipur        CSE     A     A
3  Priya     45  Mumbai         IT     B     B
4   Aman     85  Jaipur        CSE     A     A
5  Karan     72   Delhi         AI     B     B

In [49]:
df.sort_values("Marks")

    Name  Age  Marks    City Department Grade grade
3  Priya   22     45  Mumbai         IT     B     B
1   Ravi   21     60   Delhi         IT     B     B
5  Karan   23     72   Delhi         AI     B     B
0   Aman   20     85  Jaipur        CSE     A     A
4   Aman   20     85  Jaipur        CSE     A     A
2   Neha   19     92  Jaipur        CSE     A     A

In [50]:
df.sort_values("Marks",ascending=False)

    Name  Age  Marks    City Department Grade grade
2   Neha   19     92  Jaipur        CSE     A     A
0   Aman   20     85  Jaipur        CSE     A     A
4   Aman   20     85  Jaipur        CSE     A     A
5  Karan   23     72   Delhi         AI     B     B
1   Ravi   21     60   Delhi         IT     B     B
3  Priya   22     45  Mumbai         IT     B     B

In [53]:
df["City"].isnull().any()

np.False_

In [54]:
df["Marks"].fillna(0)

0    85
1    60
2    92
3    45
4    85
5    72
Name: Marks, dtype: int64

In [55]:
df

    Name  Age  Marks    City Department Grade grade
0   Aman   20     85  Jaipur        CSE     A     A
1   Ravi   21     60   Delhi         IT     B     B
2   Neha   19     92  Jaipur        CSE     A     A
3  Priya   22     45  Mumbai         IT     B     B
4   Aman   20     85  Jaipur        CSE     A     A
5  Karan   23     72   Delhi         AI     B     B

In [56]:
df[df.duplicated()]

   Name  Age  Marks    City Department Grade grade
4  Aman   20     85  Jaipur        CSE     A     A

In [58]:
df.drop_duplicates()

    Name  Age  Marks    City Department Grade grade
0   Aman   20     85  Jaipur        CSE     A     A
1   Ravi   21     60   Delhi         IT     B     B
2   Neha   19     92  Jaipur        CSE     A     A
3  Priya   22     45  Mumbai         IT     B     B
5  Karan   23     72   Delhi         AI     B     B

In [59]:
df["Marks2"]=df["Marks"].apply(lambda x:x*2)

In [60]:
df

    Name  Age  Marks    City Department Grade grade  Marks2
0   Aman   20     85  Jaipur        CSE     A     A     170
1   Ravi   21     60   Delhi         IT     B     B     120
2   Neha   19     92  Jaipur        CSE     A     A     184
3  Priya   22     45  Mumbai         IT     B     B      90
4   Aman   20     85  Jaipur        CSE     A     A     170
5  Karan   23     72   Delhi         AI     B     B     144

In [65]:
df.groupby("Department")["Name"].count()

Department
AI     1
CSE    3
IT     2
Name: Name, dtype: int64

In [66]:
df.groupby("Department")["Marks"].mean()

Department
AI     72.000000
CSE    87.333333
IT     52.500000
Name: Marks, dtype: float64

In [68]:
df.groupby("City")["Marks"].max()

City
Delhi     72
Jaipur    92
Mumbai    45
Name: Marks, dtype: int64

In [74]:
df.groupby("Department")["Marks"].agg(["min","max"])

            min  max
Department
AI           72   72
CSE          85   92
IT           45   60

In [75]:
df

    Name  Age  Marks    City Department Grade grade  Marks2
0   Aman   20     85  Jaipur        CSE     A     A     170
1   Ravi   21     60   Delhi         IT     B     B     120
2   Neha   19     92  Jaipur        CSE     A     A     184
3  Priya   22     45  Mumbai         IT     B     B      90
4   Aman   20     85  Jaipur        CSE     A     A     170
5  Karan   23     72   Delhi         AI     B     B     144

In [77]:
df.groupby("Department")["Marks"].agg(["sum","mean"])

            sum       mean
Department
AI           72  72.000000
CSE         262  87.333333
IT          105  52.500000

In [79]:
df.groupby(["City","Department"])["Marks"].sum()

City    Department
Delhi   AI             72
        IT             60
Jaipur  CSE           262
Mumbai  IT             45
Name: Marks, dtype: int64

In [80]:
df.groupby("City")["Marks"].max()

City
Delhi     72
Jaipur    92
Mumbai    45
Name: Marks, dtype: int64

In [82]:
df.pivot_table(index="City",columns="Department",values="Marks",aggfunc="mean")

Department    AI        CSE    IT
City
Delhi       72.0        NaN  60.0
Jaipur       NaN  87.333333   NaN
Mumbai       NaN        NaN  45.0

In [83]:
df

    Name  Age  Marks    City Department Grade grade  Marks2
0   Aman   20     85  Jaipur        CSE     A     A     170
1   Ravi   21     60   Delhi         IT     B     B     120
2   Neha   19     92  Jaipur        CSE     A     A     184
3  Priya   22     45  Mumbai         IT     B     B      90
4   Aman   20     85  Jaipur        CSE     A     A     170
5  Karan   23     72   Delhi         AI     B     B     144

In [84]:
df1 = pd.DataFrame({
    "Name": ["Aman", "Ravi"]
})

df2 = pd.DataFrame({
    "Name": ["Neha", "Priya", "Karan"]
})

In [85]:
df1

   Name
0  Aman
1  Ravi

In [88]:
pd.concat([df1,df2],axis=0,ignore_index=True)

    Name
0   Aman
1   Ravi
2   Neha
3  Priya
4  Karan

In [89]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ["Aman", "Ravi", "Neha", "Priya"]
})

df2 = pd.DataFrame({
    "ID": [1, 2, 3, 5],
    "Marks": [85, 60, 92, 75]
})

In [91]:
pd.merge(df1,df2,how="outer")

   ID   Name  Marks
0   1   Aman   85.0
1   2   Ravi   60.0
2   3   Neha   92.0
3   4  Priya    NaN
4   5    NaN   75.0

In [92]:
df1 = pd.DataFrame({
    "Name": ["Aman", "Ravi", "Neha"]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "Marks": [85, 60, 92]
}, index=[1, 2, 3])

In [93]:
df1.join(df2)

   Name  Marks
1  Aman     85
2  Ravi     60
3  Neha     92

In [94]:
df = pd.DataFrame({
    "Name": ["Aman", "Ravi", "Neha", "Priya"],
    "Marks": [85, None, 92, None],
    "City": ["Jaipur", None, "Delhi", "Mumbai"],
    "Age": [20, 21, None, 22]
})

In [95]:
df.isna().sum()

Name     0
Marks    2
City     1
Age      1
dtype: int64

In [96]:
df = pd.DataFrame({
    "Name": ["Aman", "Ravi", "Neha", "Priya", "Karan"],
    "Department": ["CSE", "IT", "CSE", "IT", "CSE"],
    "Marks": [85, 60, 92, 45, 72]
})

In [97]:
df

    Name Department  Marks
0   Aman        CSE     85
1   Ravi         IT     60
2   Neha        CSE     92
3  Priya         IT     45
4  Karan        CSE     72

In [102]:
df.sort_index(ascending=False)

    Name Department  Marks
4  Karan        CSE     72
3  Priya         IT     45
2   Neha        CSE     92
1   Ravi         IT     60
0   Aman        CSE     85

In [103]:
df = pd.DataFrame({
    "Name": ["Aman", "Ravi", "Neha", "Priya", "Karan"],
    "Marks": [85, 32, 92, 38, 72]
})

In [104]:
df

    Name  Marks
0   Aman     85
1   Ravi     32
2   Neha     92
3  Priya     38
4  Karan     72

In [105]:
df["Result"]=df["Marks"].apply(lambda x:"pass" if x>40 else "fail")

In [106]:
df

    Name  Marks Result
0   Aman     85   pass
1   Ravi     32   fail
2   Neha     92   pass
3  Priya     38   fail
4  Karan     72   pass