In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({
    "Name": ["Hemant", "Ravi", "Rahul", "Mohan", "Amit", "Karan"],
    "Age": [19, 20, 19, 21, 22, 20],
    "Marks": [85, 72, 90, 65, 78, 95],
    "City": ["Jaipur", "Delhi", "Jaipur", "Kota", "Delhi", "Jaipur"]
})
df

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
1    Ravi   20     72   Delhi
2   Rahul   19     90  Jaipur
3   Mohan   21     65    Kota
4    Amit   22     78   Delhi
5   Karan   20     95  Jaipur

In [4]:
df["Name"]

0    Hemant
1      Ravi
2     Rahul
3     Mohan
4      Amit
5     Karan
Name: Name, dtype: str

In [5]:
df["Marks"]

0    85
1    72
2    90
3    65
4    78
5    95
Name: Marks, dtype: int64

In [6]:
df[["Name","Age"]]

     Name  Age
0  Hemant   19
1    Ravi   20
2   Rahul   19
3   Mohan   21
4    Amit   22
5   Karan   20

In [7]:
df[["Name","Age","City"]]

     Name  Age    City
0  Hemant   19  Jaipur
1    Ravi   20   Delhi
2   Rahul   19  Jaipur
3   Mohan   21    Kota
4    Amit   22   Delhi
5   Karan   20  Jaipur

In [8]:
df.loc[3]

Name     Mohan
Age         21
Marks       65
City      Kota
Name: 3, dtype: object

In [9]:
df.loc[[0,1,2]]

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
1    Ravi   20     72   Delhi
2   Rahul   19     90  Jaipur

In [10]:
df.loc[[4,5]]

    Name  Age  Marks    City
4   Amit   22     78   Delhi
5  Karan   20     95  Jaipur

In [11]:
df.loc[2:5]

    Name  Age  Marks    City
2  Rahul   19     90  Jaipur
3  Mohan   21     65    Kota
4   Amit   22     78   Delhi
5  Karan   20     95  Jaipur

In [12]:
df

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
1    Ravi   20     72   Delhi
2   Rahul   19     90  Jaipur
3   Mohan   21     65    Kota
4    Amit   22     78   Delhi
5   Karan   20     95  Jaipur

In [13]:
df.loc[0,"Marks"]

np.int64(85)

In [14]:
df.loc[2,"Age"]

np.int64(19)

In [15]:
df.loc[3,"City"]

'Kota'

In [16]:
df.iloc[4,2]

np.int64(78)

In [17]:
df[df["Marks"]>80]

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
2   Rahul   19     90  Jaipur
5   Karan   20     95  Jaipur

In [18]:
df[df["Age"]==20]

    Name  Age  Marks    City
1   Ravi   20     72   Delhi
5  Karan   20     95  Jaipur

In [19]:
df[df["Marks"]<70]

    Name  Age  Marks  City
3  Mohan   21     65  Kota

In [20]:
df

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
1    Ravi   20     72   Delhi
2   Rahul   19     90  Jaipur
3   Mohan   21     65    Kota
4    Amit   22     78   Delhi
5   Karan   20     95  Jaipur

In [21]:
df[df["Age"]>=20]

    Name  Age  Marks    City
1   Ravi   20     72   Delhi
3  Mohan   21     65    Kota
4   Amit   22     78   Delhi
5  Karan   20     95  Jaipur

In [22]:
df[df["Marks"]!=80]

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
1    Ravi   20     72   Delhi
2   Rahul   19     90  Jaipur
3   Mohan   21     65    Kota
4    Amit   22     78   Delhi
5   Karan   20     95  Jaipur

In [23]:
df[(df["Age"]>20)&(df["Marks"]>80)]

Empty DataFrame
Columns: [Name, Age, Marks, City]
Index: []

In [24]:
df[(df["Age"]>19)|(df["Marks"]>90)]

    Name  Age  Marks    City
1   Ravi   20     72   Delhi
3  Mohan   21     65    Kota
4   Amit   22     78   Delhi
5  Karan   20     95  Jaipur

In [25]:
df[(df["City"] == "Jaipur") & (df["Marks"] > 80)]

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
2   Rahul   19     90  Jaipur
5   Karan   20     95  Jaipur

In [26]:
df[(df["City"]=="Delhi") | (df["Age"]>21)]

   Name  Age  Marks   City
1  Ravi   20     72  Delhi
4  Amit   22     78  Delhi

In [27]:
df[~(df["Age"]==20)]

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
2   Rahul   19     90  Jaipur
3   Mohan   21     65    Kota
4    Amit   22     78   Delhi

In [28]:
df

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
1    Ravi   20     72   Delhi
2   Rahul   19     90  Jaipur
3   Mohan   21     65    Kota
4    Amit   22     78   Delhi
5   Karan   20     95  Jaipur

In [29]:
df.loc[df["Marks"]>80,"Name"]

0    Hemant
2     Rahul
5     Karan
Name: Name, dtype: str

In [30]:
df.loc[df["Marks"]>80,["Name","Marks"]]

     Name  Marks
0  Hemant     85
2   Rahul     90
5   Karan     95

In [31]:
df.loc[df["City"]=="Jaipur","Name"]

0    Hemant
2     Rahul
5     Karan
Name: Name, dtype: str

In [32]:
df.loc[df["Age"]==20,["Name","City"]]

    Name    City
1   Ravi   Delhi
5  Karan  Jaipur

In [35]:
df.loc[(df["Age"]==19) & (df["Marks"]>80),["Name","Marks"]]

     Name  Marks
0  Hemant     85
2   Rahul     90

In [36]:
df[(df["Age"]>=20) & (df["Marks"]>70)]

    Name  Age  Marks    City
1   Ravi   20     72   Delhi
4   Amit   22     78   Delhi
5  Karan   20     95  Jaipur

In [37]:
df[(df["City"]=="Jaipur") & (df["Marks"]>90)]

    Name  Age  Marks    City
5  Karan   20     95  Jaipur

In [38]:
df[(df["Age"]==19) & (df["City"]=="Jaipur") & (df["Marks"]>80)]

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
2   Rahul   19     90  Jaipur

In [41]:
df.loc[(df["Marks"]>=80) & (df["Age"]<21),["Name","Age","Marks"]]

     Name  Age  Marks
0  Hemant   19     85
2   Rahul   19     90
5   Karan   20     95

In [42]:
df

     Name  Age  Marks    City
0  Hemant   19     85  Jaipur
1    Ravi   20     72   Delhi
2   Rahul   19     90  Jaipur
3   Mohan   21     65    Kota
4    Amit   22     78   Delhi
5   Karan   20     95  Jaipur

In [43]:
df.loc[2,"Marks"]

np.int64(90)

In [48]:
df.iloc[5,2]

np.int64(95)